# This code is a Qiskit project.
#
# (C) Copyright IBM 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: IBM Cloud set up
description: Set up IBM Cloud and Code Engine
inputs:
  env_name:
    required: true
  ibmcloud_secret:
    required: true
  ibmcloud_api_key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set PREVIEW_TAG
      run: |
        if "${{ inputs.env_name == 'Preview' }}" ; then
          echo "PREVIEW_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        else
          echo "PREVIEW_TAG=`node -p "'${{ inputs.env_name }}'.toLowerCase()"`" >> $GITHUB_ENV
        fi
    - name: Set APP_NAME and DOCKER_IMAGE_TAG
      run: |
        echo "APP_NAME=qiskit-docs-preview-${{ env.PREVIEW_TAG }}" >> $GITHUB_ENV
        echo "DOCKER_IMAGE_TAG=icr.io/community-digital/qiskit-docs-preview:${{ env.PREVIEW_TAG }}" >> $GITHUB_ENV
    - name: Setup IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f code-engine
        ibmcloud plugin install -f container-registry
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login -g "Quantum Community" -r "us-south" -c "${{ inputs.ibmcloud_account }}" --apikey "${{ inputs.ibmcloud_api_key }}"
    - name: Remove previous Docker image (if exists)
      run: |
        ibmcloud cr region-set global
        if ibmcloud cr image-list | grep "qiskit-docs-preview" | grep "${{ env.PREVIEW_TAG }}" ; then
          ibmcloud cr image-rm "${{ env.DOCKER_IMAGE_TAG }}"
        else
          echo "no image to remove"
        fi
    - name: Select Code Engine project
      run: ibmcloud ce project select -n "qiskit-docs-preview"
