# Refer to https://developer.crowdin.com/configuration-file/.

"preserve_hierarchy": true

files:
  [
    {
      "source": "docs/**/*",
      "translation": "translations/%two_letters_code%/%original_path%/%original_file_name%",
      "ignore":
        [
          "docs/api/qiskit/**/*",
          "docs/api/qiskit-ibm-runtime/**/*",
          "docs/api/qiskit-ibm-provider/**/*",
        ],
      "translation_replace": {
          # We don't want to include the `docs/` folder in each of our translated
          # language folders.
          "docs/": "",
        },
    },
  ]
