# Refer to https://developer.crowdin.com/configuration-file/.

"preserve_hierarchy": true

files:
  [
    {
      "source": "docs/**/*",
      "translation": "translations/%two_letters_code%/%original_path%/%original_file_name%",
      "ignore": [
          "docs/api/qiskit/**/*",
          "docs/api/qiskit-ibm-runtime/**/*",
          "docs/api/qiskit-ibm-provider/**/*",
          # TODO: remove these once switching to the official
          # open source project. For now, we have to leave these
          # off to avoid the word limit on the free plan.
          "docs/api/migration-guides/**/*",
          "docs/build/**/*",
          "docs/run/**/*",
          "docs/transpile/**/*",
          "docs/verify/**/*",
        ],
      "translation_replace": {
          # We don't want to include the `docs/` folder in each of our translated
          # language folders.
          "docs/": "",
        },
    },
  ]
