# This code is a Qiskit project.
#
# (C) Copyright IBM 2024.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Code Engine deployment
description: Deploy app to Code Engine
inputs:
  env_name:
    required: true
  ibmcloud_account:
    required: true
  ibmcloud_api_key:
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./github/actions/set-up-ibm-cloud
      with:
        env_name: ${{ inputs.env_name }}
        ibmcloud_account: ${{ inputs.ibmcloud_account }}
        ibmcloud_api_key: ${{ inputs.ibmcloud_api_key }}
    - name: Log-in into IBM Container Registry
      uses: docker/login-action@v2
      with:
        registry: icr.io
        username: iamapikey
        password: ${{ inputs.ibmcloud_api_key }}
    - name: GH deployment status (start)
      id: gh_deployment
      uses: bobheadxi/deployments@v1
      with:
        step: start
        token: ${{ github.token }}
        env: ${{ inputs.env_name }}
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Build and push to IBM registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE_TAG }}
        cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_TAG }}
        cache-to: type=inline
    - name: Determine Code Engine app status
      id: ce_command_choice
      shell: bash
      run: |
        if ibmcloud ce app list -q | grep "${{ env.APP_NAME }}" ; then
          echo "command=update" >> $GITHUB_OUTPUT
        else
          echo "command=create" >> $GITHUB_OUTPUT
        fi
    - name: Create a new preview application in Code Engine
      id: ce_app_creation
      shell: bash
      run: |
        ibmcloud ce app ${{ steps.ce_command_choice.outputs.command }} \
          --name "${{ env.APP_NAME }}" \
          --image "${{ env.DOCKER_IMAGE_TAG }}" \
          --registry-secret "ibm-container-registry" \
          --port 3000 \
          --cpu 0.5 \
          --memory 1G \
          --min 1 \
          --max 2
        echo "preview_url=$(\
          ibmcloud ce app get --name "${{ env.APP_NAME }}" --output url
        )" >> $GITHUB_OUTPUT
    - name: GH deployment status (finish)
      uses: bobheadxi/deployments@v1
      if: always()
      with:
        step: finish
        token: ${{ github.token }}
        env: ${{ steps.gh_deployment.outputs.env }}
        status: ${{ job.status }}
        override: false
        deployment_id: ${{ steps.gh_deployment.outputs.deployment_id }}
        env_url: ${{ steps.ce_app_creation.outputs.preview_url }}
