name: Content bug or inaccuracy
description: Report typos/bugs, out-of-date content, broken links
labels: ["BUG 🪲"]
assignees:
  - abbycross
  - beckykd
  - javabster

body:
  - type: markdown
    attributes:
      value: Thank you for reporting!  Please also use the search to see if there are any other relevant issues or pull requests.

  - type: textarea
    attributes:
      label: URL to the relevant documentation
      description: provide a URL and section name/paragraph if applicable
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the fix.
      description: >
        If reporting a bug, please be as specific as possible (steps to reproduce, screenshot, etc.).
    validations:
      required: true