name: ✨ Request new content
description: Make a request to the Content Team to add a new section in the docs.
labels: ["content request", "new ✨"]
assignees:
  - abbycross
  - beckykd
  - javabster

body:
  - type: markdown
    attributes:
      value: Thank you for your request!  Upon receiving your new content request, we will review it with the team. We will add anything that is  determined to be in line with the goals and intentions of this documentation.

  - type: textarea
    attributes:
      label: URL, if applicable
      description: Provide a URL and section name/paragraph where the new content belongs, if applicable.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the new content you are requesting.
      description: >
        Please give a clear and concise description. What value does the new content bring?
    validations:
      required: true

  - type: dropdown
    attributes:
      label: If this new content request is accepted, do you want to write the content?
      description:
      multiple: false
      options:
        - I will write a draft of the proposed content
        - I can help the team by providing enough information to write the material
        - I only want to review the material when it's finished
        - "no"
      default: 0
    validations:
      required: true
