name: 📱 UI issue
description: Report a rendering or other visual problem with the user interface.
labels: ["UI feedback"]
assignees:
  - abbycross
  - beckykd
  - javabster
  - Eric-Arellano

body:
  - type: markdown
    attributes:
      value: Thank you for reporting!  Please also use the search to see if there are any other relevant issues or pull requests.
  - type: markdown
    attributes:
      value: |
        ⚠️ Note that this repository is only for non-API content that is hosted at https://docs.quantum.ibm.com/.
  - type: markdown
    attributes:
      value: |
        * If your issue concerns Qiskit API content, open an issue in the [Qiskit repository](https://github.com/Qiskit/qiskit/issues/new/choose).
  - type: markdown
    attributes:
      value: |
        * If your issue concerns Qiskit Runtime API content, open an issue in the [Qiskit IBM Runtime repository](https://github.com/Qiskit/qiskit-ibm-runtime/issues/new/choose).
  - type: markdown
    attributes:
      value: |
        * If your issue concerns a Qiskit Ecosystem project, open an issue in the relevant [Ecosystem project repository](https://qiskit.github.io/ecosystem/).

  - type: textarea
    attributes:
      label: URL to the relevant documentation
      description: provide a URL and section name/paragraph if applicable
    validations:
      required: false

  - type: textarea
    attributes:
      label: Please describe the UI problem.
      description: >
        Please be as specific as possible. Include steps to reproduce, the operating system and browser you're using, a screenshot if possible, etc.
    validations:
      required: true

  - type: markdown
    attributes:
      value: Thank you for your feedback! If you are interested in joining the IBM Quantum Feedback Program, <a href="https://www.ibm.com/quantum/feedback-program">sign up here</a>.
