name: Overall impressions and feedback
description: Provide feedback that will be read by both the Docs team and the Design Research team.
labels: ["user feedback 📥 ", "content 📄"]
assignees:
  - abbycross
  - beckykd
  - javabster
  - tobi-lasisi

body:
  - type: markdown
    attributes:
      value: Thank you for offering feedback! This form is intended for general user impressions and reactions to the Qiskit and IBM Quantum documentation. If you would like to report a bug or typo, request new content, or tell us about a problem with the UI, please return to the <a href="https://github.com/Qiskit/documentation/issues/new/choose">issues</a> page and select one of the other issue types. If you have questions about this form or more information to share, please reach out to <a href="mailto:quantum.design@us.ibm.com">quantum.design@us.ibm.com</a>.

  - type: textarea
    attributes:
      label: Feedback
      description: >
        Please include as much detail as possible.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other comments
      description: >
        Is there anything else that would be important for the Design Research team to know about this feedback?
    validations:
      required: false

  - type: markdown
    attributes:
      value: Thank you for your feedback! If you are interested in joining the IBM Quantum Feedback Program, <a href="https://www.ibm.com/quantum/feedback-program">sign up here</a>.
