# Used to find all notebooks in the repo
all-notebooks = "[!.]*/**/*.ipynb"

# Always exclude notebooks matching the following patterns
notebooks-exclude = [
    "docs/api/**",
    "**/.ipynb_checkpoints/**",
]

# The following notebooks submit jobs to IBM Quantum
notebooks-that-submit-jobs = [
    "docs/start/hello-world.ipynb",
    "tutorials/build-repitition-codes/build-repitition-codes.ipynb",
    "tutorials/chsh-inequality/chsh-inequality.ipynb",
    "tutorials/grovers-algorithm/grovers.ipynb",
    "tutorials/quantum-approximate-optimization-algorithm/qaoa.ipynb",
    "tutorials/repeat-until-success/repeat-until-success.ipynb",
    "tutorials/submitting-transpiled-circuits/submitting-transpiled-circuits.ipynb",
    "tutorials/variational-quantum-eigensolver/vqe.ipynb",
]
