# Used to find all notebooks in the repo
all-notebooks = "[!.]*/**/*.ipynb"

# Always exclude notebooks matching the following patterns
notebooks-exclude = [
    "docs/api/**",
    "**/.ipynb_checkpoints/**",
]

# The following notebooks submit jobs to IBM Quantum
notebooks-that-submit-jobs = [
    "docs/start/hello-world.ipynb",
    "tutorials/build-repitition-codes/notebook.ipynb",
    "tutorials/chsh-inequality/notebook.ipynb",
    "tutorials/grovers-algorithm/notebook.ipynb",
    "tutorials/quantum-approximate-optimization-algorithm/notebook.ipynb",
    "tutorials/repeat-until-success/notebook.ipynb",
    "tutorials/submitting-transpiled-circuits/notebook.ipynb",
    "tutorials/variational-quantum-eigensolver/notebook.ipynb",
]
