# This code is a Qiskit project.
#
# (C) Copyright IBM 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# This Action runs checks things that we care about but would be
# too slow to check in every PR.

name: Extended checks
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC

  # For translations, run checks during branch builds because CI will not be triggered
  # in the automated PR to download new translations. (That's a restriction by GitHub
  # because we use the GitHub token to create the PR - a workflow can't
  # call other workflows.)
  push:
    branches:
      - main
    paths:
      - "translations/**/*"

  pull_request:
    paths:
      - "docs/api/qiskit/**/*"
      - "docs/api/qiskit-ibm-provider/**/*"
      - "docs/api/qiskit-ibm-runtime/**/*"

jobs:
  extended-checks:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Qiskit'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node.js dependencies
        run: npm ci

      - name: Check external links
        run: >
          npm run check:links --
          --qiskit-release-notes
          --current-apis
          --historical-apis
          --skip-broken-historical
          --external

      - name: Start local Docker preview
        run: |
          ./start &
          sleep 20
      - name: Check API pages render
        run: >
          npm run check-pages-render --
          --qiskit-release-notes
          --current-apis
          --historical-apis
          --translations
