# This code is a Qiskit project.
#
# (C) Copyright IBM 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Test learning platform upload tool
on:
  pull_request:
    paths:
      - "scripts/ibm-quantum-learning-uploader/**"
jobs:
  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Qiskit'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - run: |
          cd scripts/ibm-quantum-learning-uploader/test
          ./e2e-test.sh
        env:
          LEARNING_API_TOKEN: ${{ secrets.LEARNING_API_TOKEN_STAGING }}
          LEARNING_API_ENVIRONMENT: staging
