# This code is a Qiskit project.
#
# (C) Copyright IBM 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

name: Test notebooks
on:
  pull_request:
    paths:
      - "docs/**/*.ipynb"
      - "!docs/api/**/*"
  workflow_dispatch:
jobs:
  execute:
    name: Execute notebooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Qiskit IBM Runtime to save account
        # To save account; this is re-installed during the "Run tox" step
        run: pip install qiskit-ibm-runtime

      - name: Save IBM Quantum account
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        shell: python
        run: |
          from qiskit_ibm_runtime import QiskitRuntimeService
          QiskitRuntimeService.save_account(
              channel="ibm_quantum",
              token="${{ secrets.IBM_QUANTUM_TEST_TOKEN }}",
              set_as_default=True
          )

      - name: Run tox
        uses: lsst-sqre/run-tox@97818256d9fa3c72d0c12f31660718adb495a1cb
        with:
          python-version: "3.11"
          tox-envs: "py311"
