# This code is a Qiskit project.
#
# (C) Copyright IBM 2023.
#
# This code is licensed under the Apache License, Version 2.0. You may
# obtain a copy of this license in the LICENSE file in the root directory
# of this source tree or at http://www.apache.org/licenses/LICENSE-2.0.
#
# Any modifications or derivative works of this code must retain this
# copyright notice, and modified files need to carry a notice indicating
# that they have been altered from the originals.

# This Action builds the docs on `main` so that we can have a staging build of the open
# source site. It uses IBM Cloud to build the Dockerfile at the root of the repository.
#
# Note that there is no cleanup job, unlike preview-docs.yml. The workflow will replace
# the old deploy with a new one.

name: Deploy to staging

on:
  push:
    branches: [main]

jobs:
  deploy:
    if: github.repository_owner == 'Qiskit'
    uses: ./github/workflows/code-engine-preview.yml
    with:
      env_name: Staging
